return {
  {
    "nvim-treesitter/nvim-treesitter",
    highlight = { enable = true },
    opts = {
      ensure_installed = {
        "c",
        "cpp",
        "rust",
        "zig",
        "lua",
        "go",
        "python",
        "proto",
        "typescript",
        "javascript",
        "tsx",
        "bash",
        "css",
        "scss",
        "diff",
        "dockerfile",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "html",
        "sql",
        "markdown",
        "markdown_inline",
        "json",
        "jsonc",
      },
    },
  },
}
